MNT Make employee validatable
silverstripe-labs/silverstripe-frameworktest pull request #146
Opened 2023-08-08 01:05 UTC by GuySartorelli

Fix broken validation that's already there
Add email field for testing field validation

Required for 

## Issue
- https://github.com/silverstripe/silverstripe-admin/issues/1539

2023-08-08 01:06 UTC, GuySartorelli commented on code/Employee.php
> +            $result->addFieldError('Name', '"Name" can\'t be blank');
This was just plum broken. There's no such method as `error()` on `ValidationResult`.

2023-08-09 00:36 UTC, sabina-talipova requested changes

2023-08-09 00:36 UTC, sabina-talipova commented on code/Employee.php
Looks good. Could we check, please, if it appropriate, if child class already has something like the method below or user wants to override parent method.
 
```php
public function getCMSCompositeValidator(): CompositeValidator
{
    $validator = CompositeValidator::create([MyNewValidator::create(['MyRequiredField'])]);
    return $validator;
}
```

2023-08-09 00:40 UTC, GuySartorelli commented on code/Employee.php
Can you please explain why? This module only exists for us to create text fixture classes for behat tests... nobody is using or subclassing this.

2023-08-09 21:53 UTC, sabina-talipova approved these changes

2023-08-09 22:33 UTC, sabina-talipova commented on code/Employee.php
Probably, example wasn't quite proper. My concern was, will this solution work if user decided somehow to override parent method and add another validator. 
But I agree, it is not a question of `frameworktest` module.

2023-08-09 22:51 UTC, merged