MNT New tests classes to test version tags
silverstripe-labs/silverstripe-frameworktest pull request #160
Opened 2023-12-21 03:03 UTC by sabina-talipova

## Description
## Parent issue
- https://github.com/silverstripe/silverstripe-admin/issues/1593

2024-01-07 22:45 UTC, emteknetnz requested changes

2024-01-07 22:45 UTC, emteknetnz commented on code/versioned/NonVersionedParentObject.php
> +    private static $table_name = 'NonVersionedParentObject';
```suggestion
    private static $table_name = 'FrameworkTest_NonVersionedParentObject';
```

2024-01-07 22:45 UTC, emteknetnz commented on code/versioned/NonVersionedChildObject.php
> +    private static $table_name = 'NonVersionedChildObject';
```suggestion
    private static $table_name = 'FrameworkTest_NonVersionedChildObject';
```

2024-01-07 22:45 UTC, emteknetnz commented on code/versioned/VersionedChildObject.php
> +    private static $table_name = 'VersionedChildObject';
```suggestion
    private static $table_name = 'FrameworkTest_VersionedChildObject';
```

2024-01-07 22:45 UTC, emteknetnz commented on code/versioned/TestPageVersionedObject.php
> +    private static $table_name = 'FrameworkTestPage_VersionedObject';
```suggestion
    private static $table_name = 'FrameworkTest_VersionedObject';
```

2024-01-07 22:45 UTC, emteknetnz commented on code/versioned/VersionedParentObject.php
> +    private static $table_name = 'VersionedParentObject';
```suggestion
    private static $table_name = 'FrameworkTest_VersionedParentObject';
```

2024-01-07 22:45 UTC, emteknetnz commented on code/versioned/TestPageVersionedObject.php
> +class TestPageVersionedObject extends Page implements \TestPageInterface
```suggestion
class TestPageVersionedObject extends Page implements TestPageInterface
```

And add `use TestPageInterface;` above

2024-01-08 02:48 UTC, sabina-talipova commented on code/versioned/NonVersionedParentObject.php
> +    private static $table_name = 'NonVersionedParentObject';
Updated

2024-01-08 02:48 UTC, sabina-talipova commented on code/versioned/NonVersionedChildObject.php
> +    private static $table_name = 'NonVersionedChildObject';
Updated

2024-01-08 02:48 UTC, sabina-talipova commented on code/versioned/VersionedParentObject.php
> +    private static $table_name = 'VersionedParentObject';
Updated

2024-01-08 02:49 UTC, sabina-talipova commented on code/versioned/TestPageVersionedObject.php
> +class TestPageVersionedObject extends Page implements \TestPageInterface
Updated

2024-01-08 02:51 UTC, sabina-talipova commented on code/versioned/TestPageVersionedObject.php
> +    private static $table_name = 'FrameworkTestPage_VersionedObject';
Updated

2024-05-28 23:15 UTC, GuySartorelli commented
Closing - we can reference this PR if we decide to go forward with this work in the future, pending the spike.

2024-05-28 23:15 UTC, closed without merging