NEW Add NonInlineEditableExtension
silverstripe-labs/silverstripe-frameworktest pull request #172
Opened 2024-04-30 02:49 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-elemental/pull/1178

2024-04-30 04:30 UTC, emteknetnz commented on code/TestRegistryPage.php
> +if (class_exists(RegistryPage::class)) {
This was clearly wrong, it broke my first attempt at doing a shared ci run

2024-05-03 00:44 UTC, GuySartorelli requested changes
Please update the commit message - seems incorrect?

2024-05-05 23:00 UTC, emteknetnz commented
Done

2024-05-06 01:32 UTC, GuySartorelli approved these changes
LGTM, will merge when main PR has been merged

2024-05-06 02:41 UTC, merged